#
# Copyright (c) 2025-2025 Ricardo do Canto
#
# This file is part of the EnduranceTrio Tracker project.
#
# Licensed under the Functional Software License (FSL), Version 1.1, ALv2 Future License
# (the "License");
#
# You may not use this file except in compliance with the License. You may obtain a copy
# of the License at https://fsl.software/
#
# THE SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF FITNESS FOR A PARTICULAR
# PURPOSE, MERCHANTABILITY, TITLE OR NON-INFRINGEMENT.
#
# IN NO EVENT WILL WE HAVE ANY LIABILITY TO YOU ARISING OUT OF OR RELATED TO THE
# SOFTWARE, INCLUDING INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES,
# EVEN IF WE HAVE BEEN INFORMED OF THEIR POSSIBILITY IN ADVANCE.
#

app:
  initialization:
    first-account-owner: ${FIRST_OWNER:}
    first-account-key-hash: ${FIRST_HASH:}
  version: @project.version@

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%-5level] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

server:
  forward-headers: native
  port: 8081

spring:
  application:
    name: EnduranceTrio Tracker

  config:
    import: optional:application-secrets.yaml

  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      pool-name: EnduranceTrio-HikariPool
      connection-timeout: 3000
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED
    url: jdbc:h2:mem:endurancetrio_tracker;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE

  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    locations:
      - classpath:db/migration/ddl
      - classpath:db/migration/dml
    out-of-order: false
    placeholders:
      timezone: UTC
    schemas: endurancetrio_tracker
    table: flyway_schema_history
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        default_schema: endurancetrio_tracker
        format_sql: true
        jdbc:
          time_zone: UTC
        show_sql: false
        use_sql_comments: true

  h2:
    console:
      enabled: true
      path: /h2-tracker
      settings:
        trace: false
        web-allow-others: false

  messages:
    basename: messages
    encoding: UTF-8

  sql:
    init:
      mode: never

springdoc:
  api-docs:
    path: /openapi/api-docs
  swagger-ui:
    path: /openapi/swagger-ui.html
    url: /openapi/api-docs
