#
# Copyright (c) 2025-2025 Ricardo do Canto
#
# This file is part of the EnduranceTrio Tracker project.
#
# Licensed under the Functional Software License (FSL), Version 1.1, ALv2 Future License
# (the "License");
#
# You may not use this file except in compliance with the License. You may obtain a copy
# of the License at https://fsl.software/
#
# THE SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF FITNESS FOR A PARTICULAR
# PURPOSE, MERCHANTABILITY, TITLE OR NON-INFRINGEMENT.
#
# IN NO EVENT WILL WE HAVE ANY LIABILITY TO YOU ARISING OUT OF OR RELATED TO THE
# SOFTWARE, INCLUDING INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES,
# EVEN IF WE HAVE BEEN INFORMED OF THEIR POSSIBILITY IN ADVANCE.
#

cors:
  # Should be set in the .env file or as an environment variable
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

logging:
  file:
    name: "./logs/endurancetrio-tracker.log"
  level:
    com.endurancetrio: DEBUG
    org.flywaydb: DEBUG
    org.hibernate.orm.jdbc.bind: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc: DEBUG
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 20

management:
  endpoint:
    health:
      show-details: when_authorized

server:
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    # Database credentials must be set in the .env file or as an environment variable
    username: ${DB_USERNAME}
    password: ${DB_SECRET}

  flyway:
    locations:
      - classpath:db/migration/ddl/h2
      - classpath:db/migration/dml/h2

  h2:
    console:
      enabled: false

  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
