#
# Copyright (c) 2025-2025 Ricardo do Canto
#
# This file is part of the EnduranceTrio Tracker project.
#
# Licensed under the Functional Software License (FSL), Version 1.1, ALv2 Future License
# (the "License");
#
# You may not use this file except in compliance with the License. You may obtain a copy
# of the License at https://fsl.software/
#
# THE SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF FITNESS FOR A PARTICULAR
# PURPOSE, MERCHANTABILITY, TITLE OR NON-INFRINGEMENT.
#
# IN NO EVENT WILL WE HAVE ANY LIABILITY TO YOU ARISING OUT OF OR RELATED TO THE
# SOFTWARE, INCLUDING INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES,
# EVEN IF WE HAVE BEEN INFORMED OF THEIR POSSIBILITY IN ADVANCE.
#

app:
  initialization:
    first-account-owner: ${FIRST_OWNER:}
    first-account-key-hash: ${FIRST_HASH:}
  version: @project.version@

cors:
  # IMPORTANT: Use a comma-separated string for deployment flexibility.
  # This value is easily overridden by the environment variable CORS_ALLOWED_ORIGINS
  allowed-origins: "http://localhost:3000,http://localhost:8081"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%-5level] %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

server:
  forward-headers-strategy: native
  port: 8081

spring:
  application:
    name: EnduranceTrio Tracker

  config:
    import: optional:application-secrets.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: EnduranceTrio-HikariPool
      auto-commit: false
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      keepalive-time: 300000
      maximum-pool-size: 3
      max-lifetime: 1800000
      minimum-idle: 1
      transaction-isolation: TRANSACTION_READ_COMMITTED

  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    locations:
      - classpath:db/migration/ddl/postgres
      - classpath:db/migration/dml/postgres
    out-of-order: false
    placeholders:
      timezone: UTC
    schemas: endurancetrio_tracker
    table: flyway_schema_history
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        default_schema: endurancetrio_tracker
        format_sql: true
        jdbc:
          time_zone: UTC
        show_sql: false
        use_sql_comments: true

  messages:
    basename: messages
    encoding: UTF-8

  sql:
    init:
      mode: never
